parameters:
    pim_catalog.factory.family.class:                Pim\Bundle\CatalogBundle\Factory\FamilyFactory
    pim_catalog.factory.attribute_requirement.class: Pim\Bundle\CatalogBundle\Factory\AttributeRequirementFactory
    pim_catalog.factory.referenced_collection.class: Pim\Bundle\CatalogBundle\Doctrine\ReferencedCollectionFactory
    pim_catalog.factory.attribute_type.class:        Pim\Bundle\CatalogBundle\AttributeType\AttributeTypeFactory
    pim_catalog.factory.media.class:                 Pim\Bundle\CatalogBundle\Factory\MediaFactory
    pim_catalog.factory.metric.class:                Pim\Bundle\CatalogBundle\Factory\MetricFactory

services:
    pim_catalog.factory.family:
        class: %pim_catalog.factory.family.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.factory.attribute_requirement'

    pim_catalog.factory.attribute_requirement:
        class: %pim_catalog.factory.attribute_requirement.class%

    pim_catalog.factory.referenced_collection:
        class: %pim_catalog.factory.referenced_collection.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'

    pim_catalog.factory.attribute_type:
        class: %pim_catalog.factory.attribute_type.class%
        arguments: ['@service_container', ~]

    pim_catalog.factory.media:
        class: %pim_catalog.factory.media.class%
        arguments:
            - %pim_catalog.entity.product_media.class%

    pim_catalog.factory.metric:
        class: %pim_catalog.factory.metric.class%
        arguments:
            - %pim_catalog.entity.metric.class%
