parameters:
    pim_catalog.persister.product.class: Pim\Bundle\CatalogBundle\Persistence\BasicPersister

services:
    # Persister
    pim_catalog.persister.product:
        class: %pim_catalog.persister.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_catalog.manager.completeness'
