parameters:
    pim_user.event_subscriber.user_preferences.class: Pim\Bundle\UserBundle\EventSubscriber\UserPreferencesSubscriber
    pim_user.event_subscriber.group.class:            Pim\Bundle\UserBundle\EventSubscriber\GroupSubscriber

services:
    pim_user.event_subscriber.user_preferences:
        class: %pim_user.event_subscriber.user_preferences.class%
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: doctrine.event_subscriber }

    pim_user.event_subscriber.group:
        class: %pim_user.event_subscriber.group.class%
        tags:
            - { name: kernel.event_subscriber }
