Pim\Bundle\CatalogBundle\Model\ProductMedia:
    type: entity
    table: pim_catalog_product_media
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        filename:
            type: string
            length: 255
            nullable: true
        filePath:
            type: string
            length: 500
            nullable: true
            column: file_path
        originalFilename:
            type: string
            nullable: true
            column: original_filename
        mimeType:
            type: string
            length: 255
            nullable: true
            column: mime_type
    oneToOne:
        value:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductValueInterface
            mappedBy: media
            joinColumns:
                value_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
